### ISSUE TITLE
"Apply for a round" modal

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-hub#113]
**User Story**
As a project owner, 
I want to get to the round application page for my chosen grant program
so that I can apply for that round 

**Acceptance Criteria:**
[TBD] 

**Tasks**
- [ ] Determine how long we will need to store/persist round data (i.e. localstorage) 
- [ ] Be able to retain state for which grant program the user entered Grant Hub with 
- [ ] Display the grant program and/or round name in the modal text depending on the grant program/round 
- [ ] "Apply" CTA takes you to grant application page

**Link to mocks:** https://www.figma.com/file/obBzCCL8KwoTlVBb5g3ccN/Grant-Hub---Wireframes?node-id=1313%3A2598

<img width="710" alt="Screen Shot 2022-06-29 at 9 18 18 PM" src="https://user-images.githubusercontent.com/26017180/176572589-e7226d40-4926-4b96-9118-71d0ff8b0c25.png">
