### ISSUE TITLE
Editing a project bugs x3 

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-hub#223]
**Tasks**

Bugs: 
- [ ] Card preview for an edited project doesn’t update on Project Dashboard until the page is explicitly refreshed 
- [ ] After refresh, the previously uploaded logo and banner images get replaced by the default images 
- [ ] On the "Edit Project" page, the logo preview is wrong and is displaying the banner image instead
