### ISSUE TITLE
swap in new fallback logo and banner images

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-hub#324]
**User Story**
As a project owner,
I want the option to skip uploading a custom banner and/or logo image but still see default logo and banner images
so that my project still has a visual

**Acceptance Criteria:**

GIVEN that I have skipped uploading a custom banner and/or logo image
WHEN I publish my project 
THEN I see the default logo and banner images on the Project Dashboard, Project Details, & Application page

--------------------------------

**Tasks**
- [ ] When a user does not upload a banner and/or logo image, display the following fallback banner and logo image on the Project Dashboard page
- [ ] When a user does not upload a banner and/or logo image, display the following fallback banner and logo image on the  Project Details page
- [ ]  When a user does not upload a banner and/or logo image, display the following fallback banner and logo image on the project details toggle on the Round Application page

---------------------------------

**Fallback banner image**
![Image](https://user-images.githubusercontent.com/26017180/191328940-bb01735e-2bb8-4532-bd93-17ea66f1bd1c.png)

**Fallback logo image**
![Image](https://user-images.githubusercontent.com/26017180/191328947-b7ff553a-209d-43aa-b219-83da0f6a1038.png)

**Comment by michellema1208** [comment]
### ✅ Status Update: Moving to "Ready for Deployment"

@codenamejason I just tested this and it looks awesome!
