### ISSUE TITLE
general: update copy and logo throughout the app

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-hub#371]
**TASKS**

Logos: https://www.figma.com/file/eoaFuYuskh5ck11wrrAxCV/Gitcoin-Protocol-Branding?node-id=37%3A199  

**_General Landing Page_**
- [x] Update Title to "Grants Hub" 
- [x] Update to new Grants Hub logo (see branding deck above) 
- [x] Remove Body text "Build and fund your projects all in one place -- from creating a project to applying for grants to creating impact with your project starting today!" 
- [x] Update Body text to "Build and fund your projects all in one place." 

_**Tab**_
- [x] Update to new Grants Hub logo (see branding deck above) 
- [x] Update text to say "Grants Hub" 

_**Nav Bar**_
- [x] Update Title to "Grants Hub"
- [x] Update to new Grants Hub logo (see branding deck above) 

_**My Projects/Home Page**_
- [x] Remove Body text "Manage projects across multiple grants programs." 
- [x] Update Body text to "Bring your project to life." 

_**Create a Project Page**_
- [x] Update Title to "Create a Project" (should also be updated on Verification & Preview pages)
- [x] Add subheading "Project Details" 
- [x] Update Body text to "Tell us more about what you’re working on." 

For example:

![Image](https://user-images.githubusercontent.com/26017180/199841099-9ef6f123-497b-49a8-9cf8-e4c524527ebe.png)

_**Create a Project > Verification Page**_ 
- [x] Add subheading "Project Socials"
- [x] Update Body text to "Tell us more about what you’re working on." 

_**Create a Project > Project Preview Page**_ 
- [x] Add subheading "Project Preview"
- [x] Update Body text to "Here's a preview of what your project page will look like." 

**Edit Project Page**
- [x] Update Title to "Edit Your Project" (should also be updated on Verification & Preview pages)
- [x] Add subheading "Project Details" 
- [x] Update Body text to "Tell us more about what you’re working on." 

_**Edit Project > Verification Page**_ 
- [x] Add subheading "Project Socials"
- [x] Update Body text to "Tell us more about what you’re working on." 

_**Edit Project > Project Preview Page**_ 
- [x] Add subheading "Project Preview"
- [x] Update Body text to "Here's a preview of what your project page will look like." 

_**Round Application Landing Page**_
- [x] Update "Application Date" to "Application Period:"  
- [x] Update "Round Date" to "Round Dates:" 
- [x] Update CTA to "Apply" 

_**Round Application**_
- [x] Update "Application Date" to "Application Period:"  
- [x] Update "Round Date" to "Round Dates:" 

_**Round Application Banner on My Projects**_
- [x] Update CTA to "Apply"
