### ISSUE TITLE
error page: style updates to match designs 

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-hub#424]
**Tasks**
- [ ] "404 error" font size and color should match designs 
- [ ] More spacing between "contact us on Discord" and home button 
- [ ] The home in "Go back home" button should be lower case 

See [Figma](https://www.figma.com/file/obBzCCL8KwoTlVBb5g3ccN/Grant-Hub---Wireframes?node-id=2188%3A10232) for design specifications 

**Currently in app (needs to be fixed)**: 
<img width="1419" alt="Screen Shot 2022-10-02 at 2 45 55 PM" src="https://user-images.githubusercontent.com/26017180/193470778-b6ef9835-8380-46ad-bc7d-0c12ea66f86d.png">

**Designs**: 
<img width="696" alt="Screen Shot 2022-10-02 at 2 46 08 PM" src="https://user-images.githubusercontent.com/26017180/193470834-2abdfbfc-40f5-4dd5-99bb-996b6edc767a.png">
