### ISSUE TITLE
[Design] UX for navigating multiple networks 

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-hub#483]
**User story**
As a project owner, 
I want to be able to use multiple networks on Grant Hub 
so that I can create projects on networks of my choice or apply to rounds deployed on different networks 

**Tasks**
- [ ] When a user enters Grant Hub -> Create new project -> Select chain to create project on 
- [ ] If round is deployed on a different network, switch to the correct network  
- [ ] At Edit Project time, prompt user to switch to the network that the project is created on
- [ ] You should see all of your projects across different networks on "My Projects"
- [ ] Project card and Project Details should say which network your project is deployed to
