### ISSUE TITLE
landing page: update Grants Hub landing page to be consistent with other protocols

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-hub#556]
Discord discussion for context: https://discord.com/channels/562828676480237578/962026258273804398/1039958924461346827 

Current landing page: 
<img width="1431" alt="Screen Shot 2022-11-09 at 6 00 52 PM" src="https://user-images.githubusercontent.com/26017180/200960474-7eddd1f2-ed24-4d2e-8e2f-d3b061de76d0.png">

Passport landing page: 
<img width="1437" alt="passport" src="https://user-images.githubusercontent.com/26017180/200960627-a51a61c4-03d6-4a3a-9e37-e46515bbd1be.png">

**Tasks**
- [ ] Update "Grants Hub" to "Gitcoin" in all caps, size 16, font is Futura, letter spacing is 6% (see Passport landing page for reference) 
- [ ] Update "Bring your project life" to "Grants Hub" (keep current sizing / font / spacing) 
- [ ] Update "Build and fund your projects all in one place" to "Build and fund your project all in one place, and bring your vision to life."
