### ISSUE TITLE
repo refactor: migrating the contract folder

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-hub#755]
https://www.notion.so/gitcoin/Rename-Guide-4a0a9aeb0b744e75a8490ba9bf4080fc

The goal of this task is to migrate the contracts from grant-hub into grants-round/contracts package.
This should be paired by a member from both teams 

**Tasks**
- [x] move ProjectRegistry.sol to grants-round/packages/contracts/
- [x] move tests to grants-round/packages/contracts/
- [x] ensure tests run locally 
- [x] move migrations file to grants-round/packages/contracts/scripts/<new-name>
- [x] evaluate https://github.com/gitcoinco/grant-hub/blob/development/contracts/lib/utils.ts and see if we can reuse utils
- [x] update deploy script of project registry and see if we should standardize this 
- [x] run a test deployment on goerli to make sure everything works
- [x] migrate https://github.com/gitcoinco/grant-hub/tree/development/docs#chains to  https://github.com/gitcoinco/grants-round/blob/main/packages/contracts/docs/CHAINS.md
- [x] update https://github.com/gitcoinco/grants-round/blob/main/packages/contracts/docs/DEPLOY_STEPS.md
- [x] migrate https://github.com/gitcoinco/grant-hub/tree/development/contracts/.openzeppelin
- [x] auto generate docs

**Acceptance Criteria**

- Being able to deploy the project registry from the new package on goerli via the deploy script 
- Ensuring tests run locally and via CI 
- Documentation is updated to reflect the new contract
