### ISSUE TITLE
repo refactor: migrate grant-hub-dapp

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-hub#757]
Context: https://www.notion.so/gitcoin/Rename-Guide-4a0a9aeb0b744e75a8490ba9bf4080fc

**Tasks**

- [x] move dapp from grant-hub into it's own package within grants-round called `project-registry`
- [x] move grant-hub-dapp -> grants-round/packages/<new-name>
- [x] migrate github actions
- [x] ensure preview on stage env works
- [x] update fleek deploy and validate deploy works as expected

**Acceptance Criteria**
- [x] should be able to run app locally + CI 
- [x] ensure fleek env are generated for any PR raised
- [x] ensure github actions run
